
#ifndef SERLINK_CONFIG_HPP_
#define SERLINK_CONFIG_HPP_

//#define SERLINK_CONFIG__MAX_DATA_LEN 50

#define SERLINK_CONFIG__MAX_SOCKETS 5

#define SERLINK_CONFIG__SOCKET_TX_MAX_MSGS 3
#define SERLINK_CONFIG__SOCKET_RX_MAX_MSGS 3


#endif /* SERLINK_CONFIG_HPP_ */